apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-web
  labels:
    app: order-web
spec:
  selector:
    matchLabels:
      app: order-web
  template:
    metadata:
      labels:
        app: order-web
    spec:
      containers:
      - name: order-web
        image: ghcr.io/kedacore/sample-dotnet-worker-servicebus-portal
        env:
        - name: KEDA_SERVICEBUS_AUTH_MODE
          value: ConnectionString
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: order-consumer-secret
             key: queue-connection-string
        - name: KEDA_SERVICEBUS_QUEUE_NAME        
             value: orders
---
apiVersion: v1
kind: Service
metadata:
  name: kedasampleweb
  labels:
    app: order-web  
  annotations:
    # Expose service on <label-name>.<location>.cloudapp.azure.com
    service.beta.kubernetes.io/azure-dns-label-name: keda-orders-portal
spec:
  selector:
    app: order-web
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-portal
  labels:
    app: order-web
