apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-web
  labels:
    app: order-web
spec:
  selector:
    matchLabels:
      app: order-web
  template:
    metadata:
      labels:
        app: order-web
    spec:
      containers:
      - name: order-web
        image: ghcr.io/kedacore/sample-dotnet-worker-servicebus-portal
        env:
        - name: KEDA_SERVICEBUS_AUTH_MODE
          value: ConnectionString
        - name: KEDA_SERVICEBUS_QUEUE_NAME
          value: orders
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: order-consumer-secret
             key: queue-connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: kedasampleweb
  labels:
    app: order-web  
spec:
  selector:
    app: order-web
  ports:
    - protocol: TCP
      port: 80
